export default {
  nav: { home: 'Home', services: 'Services', booking: 'Book Now', gallery: 'Gallery', reviews: 'Reviews', contact: 'Contact', schedule: 'Schedule Cleaning' },
  hero: { badge: 'Top Rated Cleaning Service', title1: 'Clean Spaces,', title2: 'Clear Minds.', description: 'Experience the joy of returning to a spotless home. We provide professional, reliable, and meticulous cleaning services tailored to your lifestyle.', bookNow: 'Book Online Now', viewServices: 'View Services', satisfaction: '100% Satisfaction', guaranteed: 'Guaranteed' },
  services: { heading: 'Cleaning Services for Every Need', subheading: 'From routine tidying to deep cleans, we have a package that fits your home and your budget.' },
  booking: { heading: 'Book Your Clean in Minutes', subheading: 'Choose your service, pick a date and time that works for you, and we\'ll handle the rest.', step1: 'Step 1: Service', step2: 'Step 2: Schedule', selectService: 'What do you need help with?', homeSize: 'Home Size', homeSizePlaceholder: 'Select home size...', addOns: 'Add-ons (Optional)', continue: 'Continue to Scheduling', back: 'Back', scheduleTitle: 'Pick a Date & Time', scheduleDesc: 'Select your preferred date and time below.' },
  gallery: { heading: 'Before & After: Our Work Speaks for Itself', subheading: 'Real results from real homes. See why our clients keep coming back.', viewAll: 'View Full Gallery' },
  reviews: { heading: 'What Our Clients Say', subheading: 'Rated 4.9 / 5 from over 120+ happy reviews.', viewAll: 'View All Reviews', leaveReview: 'Leave a Review', name: 'Your Name', service: 'Service Used', rating: 'Rating', review: 'Your Review', submit: 'Submit Review', successMsg: 'Thank you for your review!' },
  contact: { heading: 'Get in Touch', subheading: 'Have a special request or need a custom quote? Reach out to us directly.', phone: 'Phone', email: 'Email', location: 'Location', locationDetail: 'Serving the Greater Metro Area', hours: 'Mon-Sat: 8am - 6pm', firstName: 'First Name', lastName: 'Last Name', emailAddress: 'Email Address', message: 'Message', messagePlaceholder: 'How can we help you?', send: 'Send Message', successMsg: 'Message sent! We\'ll be in touch shortly.' },
  footer: { tagline: 'Clean Spaces, Clear Minds. Bringing professional, detailed, and reliable cleaning services right to your doorstep.', quickLinks: 'Quick Links', hoursTitle: 'Hours', monFri: 'Mon - Sun', monFriTime: '9:00 AM - 6:00 PM', rights: '© {year} Streamline Cleaning Services. All rights reserved.', terms: 'Terms', privacy: 'Privacy', accessibility: 'Accessibility' },
  accessibility: { heading: 'Accessibility Statement', intro: 'We are committed to ensuring digital accessibility.', standards: 'Standards', standardsText: 'We aim for WCAG 2.1 Level AA.', measures: 'Measures', measure1: 'Semantic HTML', measure2: 'Colour contrast', measure3: 'Keyboard navigation', measure4: 'Alt text for images', measure5: 'Responsive design', measure6: 'Skip-to-content link', feedback: 'Feedback', feedbackText: 'Your feedback is welcome.' },
  terms: { heading: 'Terms of Service', lastUpdated: 'Last updated: January 2026', section1Title: '1. Acceptance', section1Text: 'By using this website you accept these terms.', section2Title: '2. Services', section2Text: 'We provide cleaning services.', section3Title: '3. Bookings', section3Text: 'Cancel 24 hours in advance.', section4Title: '4. Privacy', section4Text: 'See our Privacy Policy.', section5Title: '5. Liability', section5Text: 'Limited liability.', section6Title: '6. Changes', section6Text: 'We may amend these terms.' },
  privacy: { heading: 'Privacy Policy', lastUpdated: 'Last updated: January 2026', section1Title: '1. Information Collected', section1Text: 'Information you provide directly.', section2Title: '2. Use', section2Text: 'To provide our services.', section3Title: '3. Sharing', section3Text: 'We do not sell your data.', section4Title: '4. Security', section4Text: 'Industry-standard measures.', section5Title: '5. Cookies', section5Text: 'This site may use cookies.', section6Title: '6. Contact', section6Text: 'If you have questions about this Privacy Policy, please contact us at {email}.' }
};
