export default {
  nav: { home: 'Início', services: 'Serviços', booking: 'Reservar', gallery: 'Galeria', reviews: 'Avaliações', contact: 'Contato', schedule: 'Agendar Limpeza' },
  hero: { badge: 'Serviço de Limpeza Mais Bem Avaliado', title1: 'Espaços Limpos,', title2: 'Mentes Claras.', description: 'Experimente a alegria de voltar para uma casa impecável.', bookNow: 'Reserve Online', viewServices: 'Ver Serviços', satisfaction: '100% Satisfação', guaranteed: 'Garantida' },
  services: { heading: 'Serviços de Limpeza para Toda Necessidade', subheading: 'De manutenção rotineira a limpezas profundas.' },
  booking: { heading: 'Reserve em Minutos', subheading: 'Escolha seu serviço e nós cuidamos do resto.', step1: 'Passo 1: Serviço', step2: 'Passo 2: Horário', selectService: 'Do que você precisa?', homeSize: 'Tamanho da Casa', homeSizePlaceholder: 'Selecione...', addOns: 'Extras (Opcional)', continue: 'Continuar', back: 'Voltar', scheduleTitle: 'Escolha Data e Hora', scheduleDesc: 'Selecione seu horário preferido.' },
  gallery: { heading: 'Antes e Depois', subheading: 'Resultados reais.', viewAll: 'Ver Galeria' },
  reviews: { heading: 'O Que Nossos Clientes Dizem', subheading: 'Nota 4.9 / 5.', viewAll: 'Ver Todas', leaveReview: 'Deixar Avaliação', name: 'Seu Nome', service: 'Serviço Usado', rating: 'Nota', review: 'Sua Avaliação', submit: 'Enviar', successMsg: 'Obrigado pela avaliação!' },
  contact: { heading: 'Entre em Contato', subheading: 'Precisa de um orçamento personalizado?', phone: 'Telefone', email: 'E-mail', location: 'Localização', locationDetail: 'Região Metropolitana', hours: 'Seg-Sáb: 8h - 18h', firstName: 'Nome', lastName: 'Sobrenome', emailAddress: 'E-mail', message: 'Mensagem', messagePlaceholder: 'Como podemos ajudar?', send: 'Enviar', successMsg: 'Mensagem enviada!' },
  footer: { tagline: 'Espaços Limpos, Mentes Claras.', quickLinks: 'Links Rápidos', hoursTitle: 'Horário', monFri: 'Seg - Dom', monFriTime: '9:00 - 18:00', rights: '© {year} Streamline Cleaning Services.', terms: 'Termos', privacy: 'Privacidade', accessibility: 'Acessibilidade' },
  accessibility: { heading: 'Acessibilidade', intro: 'Comprometidos com acessibilidade digital.', standards: 'Padrões', standardsText: 'WCAG 2.1 Nível AA.', measures: 'Medidas', measure1: 'HTML semântico', measure2: 'Contraste de cores', measure3: 'Navegação por teclado', measure4: 'Texto alternativo', measure5: 'Design responsivo', measure6: 'Link de pular', feedback: 'Feedback', feedbackText: 'Seu feedback é bem-vindo.' },
  terms: { heading: 'Termos de Serviço', lastUpdated: 'Janeiro 2026', section1Title: '1. Aceitação', section1Text: 'Ao usar este site, você aceita estes termos.', section2Title: '2. Serviços', section2Text: 'Oferecemos serviços de limpeza.', section3Title: '3. Reservas', section3Text: 'Cancelamento com 24h de antecedência.', section4Title: '4. Privacidade', section4Text: 'Veja nossa Política de Privacidade.', section5Title: '5. Responsabilidade', section5Text: 'Responsabilidade limitada.', section6Title: '6. Alterações', section6Text: 'Podemos alterar estes termos.' },
  privacy: { heading: 'Política de Privacidade', lastUpdated: 'Janeiro 2026', section1Title: '1. Dados Coletados', section1Text: 'Informações que você fornece.', section2Title: '2. Uso', section2Text: 'Para fornecer nossos serviços.', section3Title: '3. Compartilhamento', section3Text: 'Não vendemos seus dados.', section4Title: '4. Segurança', section4Text: 'Medidas padrão da indústria.', section5Title: '5. Cookies', section5Text: 'Este site pode usar cookies.', section6Title: '6. Contato', section6Text: 'Se você tiver dúvidas sobre esta Política de Privacidade, entre em contato pelo {email}.' }
};
